# Generated by Django 3.2.4 on 2021-06-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.DateField()),
                (
                    "day_type",
                    models.CharField(
                        choices=[
                            ("homeoffice", "Day spent in homeoffice"),
                            ("work", "Commuted to work"),
                            ("sick", "Called in sick"),
                            ("vacation", "Took the day off"),
                            ("holiday", "Day off because of a holiday"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
