# Generated by Django 3.2.4 on 2021-06-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='day',
            field=models.DateField(unique=True),
        ),
    ]
